//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorConsole {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CommandLine {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommandLine() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CalculatorConsole.CommandLine", typeof(CommandLine).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binary.
        /// </summary>
        internal static string _1 {
            get {
                return ResourceManager.GetString("1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unary.
        /// </summary>
        internal static string _10 {
            get {
                return ResourceManager.GetString("10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unary.
        /// </summary>
        internal static string _11 {
            get {
                return ResourceManager.GetString("11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binary.
        /// </summary>
        internal static string _2 {
            get {
                return ResourceManager.GetString("2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binary.
        /// </summary>
        internal static string _3 {
            get {
                return ResourceManager.GetString("3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binary.
        /// </summary>
        internal static string _4 {
            get {
                return ResourceManager.GetString("4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unary.
        /// </summary>
        internal static string _5 {
            get {
                return ResourceManager.GetString("5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unary.
        /// </summary>
        internal static string _6 {
            get {
                return ResourceManager.GetString("6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unary.
        /// </summary>
        internal static string _7 {
            get {
                return ResourceManager.GetString("7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unary.
        /// </summary>
        internal static string _8 {
            get {
                return ResourceManager.GetString("8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unary.
        /// </summary>
        internal static string _9 {
            get {
                return ResourceManager.GetString("9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the operation to be performed.
        /// </summary>
        internal static string EnterOperations {
            get {
                return ResourceManager.GetString("EnterOperations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Addition.
        /// </summary>
        internal static string MenuOption_1 {
            get {
                return ResourceManager.GetString("MenuOption_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10. Cos.
        /// </summary>
        internal static string MenuOption_10 {
            get {
                return ResourceManager.GetString("MenuOption_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 11. Tan.
        /// </summary>
        internal static string MenuOption_11 {
            get {
                return ResourceManager.GetString("MenuOption_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12. Exit.
        /// </summary>
        internal static string MenuOption_12 {
            get {
                return ResourceManager.GetString("MenuOption_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Subtraction.
        /// </summary>
        internal static string MenuOption_2 {
            get {
                return ResourceManager.GetString("MenuOption_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3. Multiplication.
        /// </summary>
        internal static string MenuOption_3 {
            get {
                return ResourceManager.GetString("MenuOption_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4. Division.
        /// </summary>
        internal static string MenuOption_4 {
            get {
                return ResourceManager.GetString("MenuOption_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5. NOT.
        /// </summary>
        internal static string MenuOption_5 {
            get {
                return ResourceManager.GetString("MenuOption_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6. SquareRoot.
        /// </summary>
        internal static string MenuOption_6 {
            get {
                return ResourceManager.GetString("MenuOption_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7. Increment.
        /// </summary>
        internal static string MenuOption_7 {
            get {
                return ResourceManager.GetString("MenuOption_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8. Decrement.
        /// </summary>
        internal static string MenuOption_8 {
            get {
                return ResourceManager.GetString("MenuOption_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9. Sine.
        /// </summary>
        internal static string MenuOption_9 {
            get {
                return ResourceManager.GetString("MenuOption_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12.
        /// </summary>
        internal static string OperationCount {
            get {
                return ResourceManager.GetString("OperationCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try Again ? Press 1 for Yes or any other number for No.
        /// </summary>
        internal static string RetryOperation {
            get {
                return ResourceManager.GetString("RetryOperation", resourceCulture);
            }
        }
    }
}
