//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ButtonEventResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ButtonEventResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsFormsApp.ButtonEventResource", typeof(ButtonEventResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grapecity.Internship.Assignments.CalculatorWinForm.Controls.FactorialCaluclation, WindowsFormsApp.
        /// </summary>
        internal static string _ {
            get {
                return ResourceManager.GetString("!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grapecity.Internship.Assignments.CalculatorWinForm.Controls.PlusMinus, WindowsFormsApp.
        /// </summary>
        internal static string ___ {
            get {
                return ResourceManager.GetString("+/-", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grapecity.Internship.Assignments.CalculatorWinForm.Controls.InverseCalulation, WindowsFormsApp.
        /// </summary>
        internal static string _1_x {
            get {
                return ResourceManager.GetString("1/x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grapecity.Internship.Assignments.CalculatorWinForm.Controls.CosineCalculation, WindowsFormsApp.
        /// </summary>
        internal static string Cos {
            get {
                return ResourceManager.GetString("Cos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grapecity.Internship.Assignments.CalculatorWinForm.Controls.LnCalculation, WindowsFormsApp.
        /// </summary>
        internal static string Ln_x {
            get {
                return ResourceManager.GetString("Ln x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grapecity.Internship.Assignments.CalculatorWinForm.Controls.LogCalculation, WindowsFormsApp.
        /// </summary>
        internal static string Log_x {
            get {
                return ResourceManager.GetString("Log x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grapecity.Internship.Assignments.CalculatorWinForm.Controls.SineCalculation, WindowsFormsApp.
        /// </summary>
        internal static string Sin {
            get {
                return ResourceManager.GetString("Sin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grapecity.Internship.Assignments.CalculatorWinForm.Controls.SquareRootCalculation, WindowsFormsApp.
        /// </summary>
        internal static string Sq__Rt_ {
            get {
                return ResourceManager.GetString("Sq. Rt.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grapecity.Internship.Assignments.CalculatorWinForm.Controls.TangentCalculation, WindowsFormsApp.
        /// </summary>
        internal static string Tan {
            get {
                return ResourceManager.GetString("Tan", resourceCulture);
            }
        }
    }
}
